config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  # authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  devise_scope :user do
    post '/fill_email' => 'oauth_callbacks#fill_email'
  end

  concern :votable do
    member do
      post :vote_up, :vote_down
    end
  end

  get '/search', to: 'search#search'

  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    resources :answers, concerns: :votable, shallow: true, except: [:index] do
      resources :comments, only: :create, defaults: { commentable: 'answers' }
      patch "best_answer", on: :member, as: :best
    end
    resources :subscribers, only: %i[create destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, except: %i[new edit] do
        resources :answers, shallow: true, except: %i[new edit]
      end
    end
  end

  resources :attachments, only: :destroy
  resources :profits, only: :index
  root to: 'questions#index'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_authorization_check  only: :search

  def search
    @search_results = SearchService.call(params[:search_string], params[:search_scope])
  end
end

app/views/search/_answer.html.slim
b Answer:
= result.body
= link_to '_link_to', question_path(result.question), target: '_blank'

app/views/search/_comment.html.slim
b Comment:
= result.body
- if result.commentable_type.downcase == 'question'
  = link_to '_link_to', question_path(result.commentable), target: '_blank'
- else
  = link_to '_link_to', question_path(result.commentable.question), target: '_blank'

app/views/search/_form.html.slim
.search
  = form_tag search_path, method: :get do
    P
    = text_field_tag 'search_string', params[:search_string], type: :search
    = select_tag :search_scope, options_for_select(SearchService::SCOPES), { include_blank: 'All' }
    = submit_tag 'Sphinx_Search'

app/views/search/_question.html.slim
b Question:
= result.body
= link_to '_link_to', question_path(result), target: '_blank'

app/views/search/_user.html.slim
b User:
= result.email

app/views/search/search.html.slim
.search_results
  h3 Search results:
  - if @search_results.empty?
    span.result Nothing was found.
  - @search_results.each do |result|
    p.result
      = render partial: "search/#{result.class.name.downcase}", locals: { result: result }