config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  # authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  devise_scope :user do
    post '/fill_email' => 'oauth_callbacks#fill_email'
  end

  concern :votable do
    member do
      post :vote_up, :vote_down
    end
  end

  get '/search', to: 'search#search'

  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    resources :answers, concerns: :votable, shallow: true, except: [:index] do
      resources :comments, only: :create, defaults: { commentable: 'answers' }
      patch "best_answer", on: :member, as: :best
    end
    resources :subscribers, only: %i[create destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, except: %i[new edit] do
        resources :answers, shallow: true, except: %i[new edit]
      end
    end
  end

  resources :attachments, only: :destroy
  resources :profits, only: :index
  root to: 'questions#index'

end

app/views/shared/_add_files.html.slim
= form_with model: @question, local: true do |f|
  table
    tr
      td = f.label :files
      td = f.file_field :files, multiple: true, direct_upload: true

app/views/shared/_attached_files.html.slim
- if resource.files.attached?
  - resource.files.each do |file|
    div id = "file_#{file.id}"
      table
        tr
          td = link_to file.filename, url_for(file)
          - if current_user&.author?(resource)
            td = link_to 'Remove file', attachment_path(file),remote: true, method: :delete

app/views/shared/_attached_links.html.slim
b Links:
ul
  - resource.links.each do |link|
    li
      - if link.gist?
        code gist="#{link.url}.json" Loading gist
      - else
        = link_to link.name, link.url

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b = "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li = message

app/views/shared/_footer.html.slim
hr
| Copyright © 2019 Brovkin Oleg

app/views/shared/_link_fields.html.slim
.nested-fields
  .link_form
    p
      = f.label :name, 'Link name'
      = f.text_field :name
    p
      = f.label :url
      = f.text_area :url
      = link_to_remove_association f

app/views/shared/_profit.html.slim
= var.fields_for :profit do |profit|
  p
    = profit.label :name, 'Profit_name'
    = profit.text_field :name
  p
    = profit.label :image, 'Profit_image'
    = profit.file_field :image, direct_upload: true

app/views/shared/_profits.html.slim
= var.fields_for :profit do |profit|
  p
    = profit.label :name, 'Profit_name'
    = profit.text_field :name
  p
    = profit.label :image, 'Profit_image'
    = profit.file_field :image, direct_upload: true

app/views/shared/_signed.html.slim
- if user_signed_in?
  p = link_to 'Sign out', destroy_user_session_path, method: :delete
-else
  p = link_to 'Sign in', new_user_session_path

app/views/shared/_votes.html.slim
.vote
  = button_to  'Like', polymorphic_url(resource, action: :vote_up),
            class: 'vote_up',
            method: :post, remote: true, data: { type: :json }

  = button_to  'Dislike', polymorphic_url(resource, action: :vote_down),
            class: 'vote_down',
            method: :post, remote: true, data: { type: :json }
.votes

app/views/shared/email.html.slim
= form_with url: fill_email_path, method: :post do |form|
  p
    b Your Email
  p
    = form.label :email
  p
    = form.email_field  :email
  p
    = form.submit 'save'