config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  # authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  devise_scope :user do
    post '/fill_email' => 'oauth_callbacks#fill_email'
  end

  concern :votable do
    member do
      post :vote_up, :vote_down
    end
  end

  get '/search', to: 'search#search'

  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    resources :answers, concerns: :votable, shallow: true, except: [:index] do
      resources :comments, only: :create, defaults: { commentable: 'answers' }
      patch "best_answer", on: :member, as: :best
    end
    resources :subscribers, only: %i[create destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, except: %i[new edit] do
        resources :answers, shallow: true, except: %i[new edit]
      end
    end
  end

  resources :attachments, only: :destroy
  resources :profits, only: :index
  root to: 'questions#index'

end

app/models/answer.rb
class Answer < ApplicationRecord
  include LinksAssociations
  include Votable
  include HasComments

  belongs_to :question, touch: true
  belongs_to :user

  has_many_attached :files

  validates :body, presence: true

  default_scope { order(best: :desc).order(:created_at) }

  after_commit :send_inform_email, on: :create

  def best_answer!
    transaction do
      question.answers.update_all(best: false)
      self.update!(best: true)
      question.profit&.update!(user: user)
    end
  end

  private

  def send_inform_email
    NotifyNewAnswerJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_answer, only: [:edit, :update, :destroy, :best_answer]
  before_action :load_question
  after_action :publish_answer, only: :create

  authorize_resource

  def new
    @answer = Answer.new
  end

  def create
    @answer = current_user.answers.create(answer_params.merge(question: @question))
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def edit; end

  def destroy
    @answer.destroy
  end

  def best_answer
    @answer.best_answer!
  end

  private

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast("questions/#{@answer.question_id}/answers", @answer.to_json)
  end

  def load_question
    @question ||= params[:question_id] ? Question.find(params[:question_id]) : load_answer.question
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [],
                                          links_attributes: %i[id name url _destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController

  before_action :find_answer, only: %i[show update destroy]
  before_action :find_question, only: %i[create index]

  def show
    render json: @answer, serializer: AnswerSerializer
  end

  def index
    answers = @question.answers
    render json: answers, each_serializer: AnswersSerializer
  end

  def create
    answer = @question.answers.build(answer_params)
    answer.user = current_resource_owner
    if answer.save
      render json: answer, status: :created
    else
      render json: { errors: answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      head :ok
    else
      head :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy
  end

  private

  def find_answer
    @answer ||= Answer.find(params[:id])
  end

  def find_question
    @question ||= Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[id name url _destroy])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache [answer, current_user]
  div id = "answer_#{answer.id}"
    p = answer.body
    div id = "comments_answer_#{answer.id}"
      = render answer.comments
      = render 'comments/form', commentable: answer

    - if answer.best?
      h4 = 'This answer is the best!'

    b Answer Vote

    - if can? :vote_up, answer
      = render 'shared/votes', resource: answer

    .links
      = render 'shared/attached_links', resource: answer

    - if can? :update, answer
      table
        tr
          td = link_to 'Delete', answer_path(answer), id: "delete-answer_#{answer.id}", \
               remote: true, method: :delete
          td = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

          - if can? :best_answer, answer
            - if !answer.best?
              td = link_to 'Best answer', best_answer_path(answer), method: :patch, remote: true

    = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      p
        = f.label :body, 'Body_Edit'
        = f.text_area :body
      p
        = render 'shared/attached_files', resource: answer
      p
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true

      .edit_links
        = f.fields_for :links do |l|
          = render 'shared/link_fields', f: l
        .add_links
          = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'
      p
        = f.submit 'Save'
    hr

app/views/answers/_form.html.slim
= form_for [@answer.question, @answer], local: true do |f|
  = f.label :body, 'Answer'
  = f.text_area :body
  p
  = f.label :files
  = f.file_field :files, multiple: true, direct_upload: true
  p = f.submit 'Create'

app/views/answers/best_answer.js.erb
$('.answers').html('<%= j render @answer.question.answers %>');

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.new_answer').remove();
  $('.answers').append('<%= j render @answer %>',
                       '<%= j render 'questions/form' %>');
<% end %>

app/views/answers/destroy.js.erb
$('#answer_<%= @answer.id %>').remove();

app/views/answers/new.html.slim
p = render 'answers/form'
p = render 'shared/footer', local: true

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.errors.blank? %>
$('.answers').html('<%= j render @question.answers %>');
<% end %>