config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  # authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  devise_scope :user do
    post '/fill_email' => 'oauth_callbacks#fill_email'
  end

  concern :votable do
    member do
      post :vote_up, :vote_down
    end
  end

  get '/search', to: 'search#search'

  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    resources :answers, concerns: :votable, shallow: true, except: [:index] do
      resources :comments, only: :create, defaults: { commentable: 'answers' }
      patch "best_answer", on: :member, as: :best
    end
    resources :subscribers, only: %i[create destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, except: %i[new edit] do
        resources :answers, shallow: true, except: %i[new edit]
      end
    end
  end

  resources :attachments, only: :destroy
  resources :profits, only: :index
  root to: 'questions#index'

end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :user, :question, presence: true
  validates :question_id, uniqueness: { scope: :user_id }
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: :create

  authorize_resource

  def create
    @subscriber = current_user.subscribers.create(question: @question)
  end

  def destroy
    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy
  end

  private

  def find_question
    @question ||= Question.find(params[:question_id])
  end
end

app/views/subscribers/_subscriber.html.slim
- if current_user&.subscribed?(question)
  -if can? :destroy, Subscriber
    = button_to 'unsubscribe!', subscriber_path(current_user.find_subscriber(question)), remote: true, method: :delete
- else
  -if can? :create, Subscriber
    = button_to 'subscribe!', question_subscribers_path(question), method: :post, remote: true, params: { question_id: question.id }

app/views/subscribers/create.js.erb
<% if @subscriber.errors.present? %>
  $('.subscribers').html('<%= render 'shared/errors', resource: @subscriber %>')
<% else %>
  $('.subscribers').html("<%= j render 'subscribers/subscriber', question: @subscriber.question %>");
<% end %>

app/views/subscribers/destroy.js.erb
$('.subscribers').html("<%= j render 'subscribers/subscriber', question: @subscriber.question %>");